// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrazioneTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrazione() {
    // Test name: Registrazione
    // Step # | name | target | value | comment
    // 1 | open | http://localhost/YourBook_war_exploded/index.jsp |  | 
    driver.get("http://localhost/YourBook_war_exploded/index.jsp");
    // 2 | click | css=.nav-item:nth-child(7) > .nav-link |  | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(7) > .nav-link")).click();
    // 3 | click | linkText=Registrati |  | 
    driver.findElement(By.linkText("Registrati")).click();
    // 4 | click | id=nome |  | 
    driver.findElement(By.id("nome")).click();
    // 5 | type | id=nome | mario rossi | 
    driver.findElement(By.id("nome")).sendKeys("mario rossi");
    // 6 | type | id=email | mario@rossi.mr | 
    driver.findElement(By.id("email")).sendKeys("mario@rossi.mr");
    // 7 | type | id=pwd | Serena99 | 
    driver.findElement(By.id("pwd")).sendKeys("Serena99");
    // 8 | type | id=pwdConf | Serena99 | 
    driver.findElement(By.id("pwdConf")).sendKeys("Serena99");
    // 9 | click | id=eta |  | 
    driver.findElement(By.id("eta")).click();
    // 10 | select | id=eta | label=23 | 
    {
      WebElement dropdown = driver.findElement(By.id("eta"));
      dropdown.findElement(By.xpath("//option[. = '23']")).click();
    }
    // 11 | click | id=registrami |  | 
    driver.findElement(By.id("registrami")).click();
  }
}
